servicea:
  image: alpine:latest
  env_file: ./services/servicea/env_file
  command: /bin/true

servicea_api:
  extends:
    file: ./docker-compose.yml
    service: servicea
  command: "echo 'root' && env"
